modLoader = "javafml"
loaderVersion = "[43,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/axelrindle/forge-chicken-drop-feathers/issues"

[[mods]]
modId = "chickendropfeathersmod"
version = "${version}"
displayName="Chicken Drop Feathers"
authors = "lalo5"
description = '''
Chicken will drop feathers from time to time.
'''
credits="Thanks to Mojang as well as the Forge and FML guys."
logoFile="logo.png"
displayURL="https://github.com/axelrindle/forge-chicken-drop-feathers"
