package de.axelrindle.chickendropfeathersmod

import net.minecraftforge.common.MinecraftForge
import net.minecraftforge.fml.common.Mod
import net.minecraftforge.fml.common.Mod.EventHandler
import net.minecraftforge.fml.common.event.FMLInitializationEvent
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent

@Suppress("unused", "UNUSED_PARAMETER", "MemberVisibilityCanBePrivate")
@Mod(modid = ChickenDropFeathersMod.MODID, name = ChickenDropFeathersMod.NAME, version = ChickenDropFeathersMod.VERSION,
        modLanguageAdapter = "net.shadowfacts.forgelin.KotlinAdapter",
        acceptedMinecraftVersions = "[1.12,1.12.2]",
        dependencies = "required-after:forgelin;")
object ChickenDropFeathersMod {

    const val MODID = "chickendropfeathersmod"
    const val NAME = "Chicken Drop Feathers"
    const val VERSION = "@VERSION@"

    @EventHandler
    fun preInit(event: FMLPreInitializationEvent) {
        val meta = event.modMetadata

        meta.autogenerated = false
        meta.modId = MODID
        meta.name = NAME
        meta.description = "Chicken will drop feathers from time to time."
        meta.version = VERSION
        meta.authorList = listOf("lalo5")
        meta.url = "https://github.com/axelrindle/forge-chicken-drop-feathers"
    }

    @EventHandler
    fun init(event: FMLInitializationEvent) {
        MinecraftForge.EVENT_BUS.register(EntitySpawnHandler())
    }
}