name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-forge:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./forge
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./forge

  build-fabric:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        download_url="https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16.0.1%2B9/OpenJDK16U-jdk_x64_linux_hotspot_16.0.1_9.tar.gz"
        wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/java_package.tar.gz
        java-version: '16'
        architecture: x64
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./fabric
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./fabric
    - name: capture build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Fabric Artifacts
        path: fabric/build/libs/
